[book]
title = "User Guide"
description = "User documentation for the Nicolino static site generatori [WIP]"
authors = ["Roberto Alsina"]

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/ralsina/nicolino"
edit-url-template = "https://github.com/ralsina/nicolino/edit/main/content/books/user-guide/{path}"
